name: FestiveArrows
main: me.yukonapplegeek.festivearrows.FestiveArrows
version: 1.0
authors: [YukonAppleGeek, VirusTotal]
commands:
   letitgoboom:
      description: Let it go BOOM!
      usage: /<command>
      permission: festivearrows.letitgoboom
      permission-message: You don't have permission
